"""FastAPI application for the REST API entrypoint.

Replaces the Connexion 3 app. The OpenAPI document and Swagger UI are generated by
FastAPI; routes live in ``routes.py``; error mapping and status-class logging are
registered here.
"""

import logging

from fastapi import FastAPI

from rdf_differ import config
from rdf_differ.api.entrypoints._logging import add_request_logging
from rdf_differ.api.entrypoints.api.exceptions import register_exception_handlers
from rdf_differ.api.entrypoints.api.routes import router

logger = logging.getLogger(config.RDF_DIFFER_LOGGER)


def create_app() -> FastAPI:
    """Build and wire the REST API FastAPI application."""
    app = FastAPI(
        title="RDF Diffing Service",
        description="Calculate the difference between two versions of the same dataset.",
        version="1.0.1",
        docs_url="/docs" if config.SHOW_SWAGGER_UI else None,
        redoc_url=None,
    )
    app.include_router(router)
    register_exception_handlers(app, logger)
    add_request_logging(app, logger)
    return app


app = create_app()
