version: '3.7'

services:
  rdf-differ-api:
    container_name: rdf-differ-api
    image: meaningfy/rdf-differ-api:latest
    build:
      context: ..
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ..:/usr/src/app
      - rdf-differ-template:${RDF_DIFFER_TEMPLATE_LOCATION}
    ports:
      - ${RDF_DIFFER_API_PORT}:${RDF_DIFFER_API_PORT}
    env_file: .env
    networks:
      - mydefault
    depends_on:
      - redis

  rdf-differ-ui:
    container_name: rdf-differ-ui
    image: meaningfy/rdf-differ-ui:latest
    build:
      context: ..
      dockerfile: ./docker/ui/Dockerfile
    volumes:
      - ..:/usr/src/app
    ports:
      - ${RDF_DIFFER_UI_PORT}:${RDF_DIFFER_UI_PORT}
    env_file: .env
    networks:
      - mydefault

  fuseki:
    container_name: fuseki
    image: meaningfy/fuseki:latest
    build:
      context: ..
      dockerfile: ./docker/fuseki/Dockerfile
    volumes:
      - ${PWD}/${RDF_DIFFER_FUSEKI_DATA_FOLDER}/fuseki:/fuseki
    env_file: .env
    environment:
      - ADMIN_PASSWORD=${RDF_DIFFER_FUSEKI_ADMIN_PASSWORD}
      - JVM_ARGS=${RDF_DIFFER_FUSEKI_JVM_ARGS}
    ports:
      - ${RDF_DIFFER_FUSEKI_PORT}:${RDF_DIFFER_FUSEKI_PORT}
    networks:
      - mydefault

  celery-worker:
    container_name: celery-worker
    build:
      context: ..
      dockerfile: ./docker/api/Dockerfile
    command: celery -A rdf_differ.services.tasks.celery_worker worker --loglevel info --logfile celery/logs/celery.log
    volumes:
      - ..:/usr/src/app
      - rdf-differ-template:${RDF_DIFFER_TEMPLATE_LOCATION}
    env_file: .env
    networks:
      - mydefault
    depends_on:
      - rdf-differ-api
      - redis

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - mydefault

  dashboard:
    build:
      context: ..
      dockerfile: ./docker/api/Dockerfile
    command: celery -A rdf_differ.services.tasks.celery_worker --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5555:5555
    depends_on:
      - rdf-differ-api
      - celery-worker
      - redis
    networks:
      - mydefault

volumes:
  rdf-differ-template:
    external: true

networks:
  mydefault:
    name: globalnet
